### ISSUE TITLE
ATParser::getSocketFromInput: return bool

### ISSUE THREAD

**Issue by bruenn** [polybassa/STM_HAL#34]
In my opinion this function and all the call sites would look much simpler if the return value would be of type bool.
with true == AT::Return_t::FINISHED and false == AT::Return_t::ERROR

```
bool ATParser::getSocketFromInput(size_t& socket, char* const termination,
                                          std::chrono::milliseconds timeout) const
{
    if (getNumberFromInput(socket, termination, timeout) != AT::Return_t::FINISHED) {
        return false;
    }
    return socket <= 6;
}
// calling it:
if (!mParser->getSocketFromInput(mSocket)) {
        Trace(ZONE_ERROR, "socket\r\n");
        return Return_t::ERROR;
    }
```
https://github.com/polybassa/Dongle/blob/c519b56815013d07265ab4d99bff96a48d79b7bf/sources/app/AT_Parser.cpp#L712

**Comment by bruenn** [comment]
the same thing applies to:
`ATParser::getNumberFromInput`

**Comment by polybassa** [comment]
I agree.
