### ISSUE TITLE
AT_Parser: Why is sievedResponses required?

### ISSUE THREAD

**Issue by bruenn** [polybassa/STM_HAL#35]
You are copying from and to possibleResponses. Why not sieve directly in possibleResponses?
While at rewriting the loop you could count, too.
```
size_t possibleResponsesCount = 0;
for (size_t i = 0; i < possibleResponses.size(); ++i) {
    const auto next = possibleResponses[i];
    if (next && currentData != next->mResponse.substr(0, currentPos)) {
        possibleResponses[i] = nullptr;
        ++possibleResponsesCount;
    }
}
```
Another benefit of counting directly, you could use the count as index and automatically sort the array (remove empty places). combine that into a data structure and the code becomes even more clear.
https://github.com/polybassa/Dongle/blob/c519b56815013d07265ab4d99bff96a48d79b7bf/sources/app/AT_Parser.cpp#L601

**Comment by bruenn** [comment]
Don't use the last version it is bugged. This started as an attempt to optimize the first version better.

init possibleresponsesCount within resetPossibleResponses()
```
size_t possibleResponsesCount = possibleResponses.size();
...
size_t stillMatchingCount = 0;
for (size_t i = 0; i < possibleResponsesCount; ++i) {
    const auto next = possibleResponses[i];
    if (next && currentData == next->mResponse.substr(0, currentPos)) {
        possibleResponses[stillMatchingCount++] = next;
    }
}
possibleResponsesCount = stillMatchingCount;
```
Now, if possibleResponsesCount == 1 you immediately know it is at index 0 and you don't have to start another search.
go and find the bugs in this loop ;-)

**Comment by polybassa** [comment]
Nice code. Would make the loop better. I don't see a bug in it right know. Did you put one in?

**Comment by bruenn** [comment]
No. Not intentionally ;-)

Am 10. November 2018 17:27:08 MEZ schrieb Nils Weiss <notifications@github.com>:
>Nice code. Would make the loop better. I don't see a bug in it right
>know. Did you put one in? 
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/polybassa/Dongle/issues/6#issuecomment-437595974

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
