### ISSUE TITLE
Obfuscation: Task Priorities

### ISSUE THREAD

**Issue by HeMe2** [polybassa/STM_HAL#54]
Hi Polybassa, 
I noticed, that in most projects, you're using a `configMAX_PRIORITY` of 15 in your FreeRTOSConfig. At the same time, in os_Task.h the `os::Task::Priority::HIGHEST` is set to a value of 15 as well. 
The FreeRTOS documentation says, that task priorities can be set in the range from 0 to (configMAX_PRIORITIES - 1). (https://www.freertos.org/RTOS-task-priority.html)

A quick look into the task.c of FreeRTOS v10.1.1 reveales, that a priority greater or equal to `configMAX_PRIORITIES` will be set to `(configMAX_PRIORITIES - 1)` automatically, when the task is created. 
```
/* This is used as an array index so must ensure it's not too large.  First
remove the privilege bit if one is present. */
if( uxPriority >= ( UBaseType_t ) configMAX_PRIORITIES )
{
	uxPriority = ( UBaseType_t ) configMAX_PRIORITIES - ( UBaseType_t ) 1U;
}
```
(task.c line 941 to 946 of FreeRTOS v10.1.1)

I think there is a bit of obfuscation on this point, because all tasks with the `Priority::HIGHEST` are created with a priority of 14. 

There are two possibilities to correct this flaw:
1. Adjust all project configurations to a maximum priority of 16.
2. The priority of `Priority::HIGHEST` can be altered to be 14 right away. There is no reason for the gap of 2 between `VERY_HIGH` and `HIGHEST` anyway. 

I don't know which of the two you'd prefer, so I opened this issue.

**Comment by polybassa** [comment]
Thanks for this issue.

Great that you dig into it. I would prefer option 2.

Will you make a PR?




Mit freundlichen Grüßen 

Nils Weiß

**Comment by HeMe2** [comment]
I created a pull request. 
I also adapted the lowest priority to zero to be consistent.
